#ifndef CONSTANTS_H
#define CONSTANTS_H

const int BACKGROUD_COLOR_R = 223;
const int BACKGROUD_COLOR_G = 223;
const int BACKGROUD_COLOR_B = 223;

const int INIT_BASIC_NODE_COLOR_R = 203;
const int INIT_BASIC_NODE_COLOR_G = 20;
const int INIT_BASIC_NODE_COLOR_B = 106;

#endif // CONSTANTS_H
